concurrency:
  cancel-in-progress: false
  group: main-push
jobs:
  apply:
    defaults:
      run:
        working-directory: terraform
    environment: production
    needs:
      - plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: canidae-solutions/lix-quick-install-action@v4
      - name: Install tofu
        run: nix profile install .#tofu
      - id: app-token
        name: Generate GitHub App token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.GH_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PEM_KEY }}
          repositories: terraform-state
      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform
      - env:
          GIT_PASSWORD: ${{ steps.app-token.outputs.token }}
          GIT_USERNAME: x-access-token
          TF_VAR_github_app_id: ${{ vars.GH_APP_ID }}
          TF_VAR_github_app_installation_id: ${{ vars.GH_APP_INSTALLATION_ID }}
          TF_VAR_github_app_pem_key: ${{ secrets.GH_APP_PEM_KEY }}
          TF_VAR_state_encryption_passphrase: ${{ secrets.TF_STATE_PASSPHRASE }}
        name: tofu init
        run: tofu init -input=false
      - env:
          GIT_PASSWORD: ${{ steps.app-token.outputs.token }}
          GIT_USERNAME: x-access-token
          TF_VAR_github_app_id: ${{ vars.GH_APP_ID }}
          TF_VAR_github_app_installation_id: ${{ vars.GH_APP_INSTALLATION_ID }}
          TF_VAR_github_app_pem_key: ${{ secrets.GH_APP_PEM_KEY }}
          TF_VAR_state_encryption_passphrase: ${{ secrets.TF_STATE_PASSPHRASE }}
        name: tofu apply
        run: tofu apply -input=false tfplan
  plan:
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: canidae-solutions/lix-quick-install-action@v4
      - name: Install tofu
        run: nix profile install .#tofu
      - id: app-token
        name: Generate GitHub App token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.GH_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PEM_KEY }}
          repositories: terraform-state
      - env:
          GIT_PASSWORD: ${{ steps.app-token.outputs.token }}
          GIT_USERNAME: x-access-token
          TF_VAR_github_app_id: ${{ vars.GH_APP_ID }}
          TF_VAR_github_app_installation_id: ${{ vars.GH_APP_INSTALLATION_ID }}
          TF_VAR_github_app_pem_key: ${{ secrets.GH_APP_PEM_KEY }}
          TF_VAR_state_encryption_passphrase: ${{ secrets.TF_STATE_PASSPHRASE }}
        name: tofu init
        run: tofu init -input=false
      - env:
          TF_VAR_github_app_id: ${{ vars.GH_APP_ID }}
          TF_VAR_github_app_installation_id: ${{ vars.GH_APP_INSTALLATION_ID }}
          TF_VAR_github_app_pem_key: ${{ secrets.GH_APP_PEM_KEY }}
          TF_VAR_state_encryption_passphrase: ${{ secrets.TF_STATE_PASSPHRASE }}
        name: tofu validate
        run: tofu validate -no-color
      - env:
          GIT_PASSWORD: ${{ steps.app-token.outputs.token }}
          GIT_USERNAME: x-access-token
          TF_VAR_github_app_id: ${{ vars.GH_APP_ID }}
          TF_VAR_github_app_installation_id: ${{ vars.GH_APP_INSTALLATION_ID }}
          TF_VAR_github_app_pem_key: ${{ secrets.GH_APP_PEM_KEY }}
          TF_VAR_state_encryption_passphrase: ${{ secrets.TF_STATE_PASSPHRASE }}
        name: tofu plan
        run: tofu plan -no-color -input=false -out=tfplan
      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
name: Push
"on":
  push:
    branches:
      - main
    paths:
      - terraform/**
      - flake.nix
      - flake.lock
      - .github/workflows/**
permissions:
  contents: read
